# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'limit_ayarlari.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 459)
        self.cb_sensor = QtWidgets.QComboBox(Dialog)
        self.cb_sensor.setGeometry(QtCore.QRect(150, 160, 201, 31))
        self.cb_sensor.setObjectName("cb_sensor")
        self.line_min = QtWidgets.QLineEdit(Dialog)
        self.line_min.setGeometry(QtCore.QRect(100, 250, 121, 31))
        self.line_min.setObjectName("line_min")
        self.line_max = QtWidgets.QLineEdit(Dialog)
        self.line_max.setGeometry(QtCore.QRect(280, 250, 131, 31))
        self.line_max.setObjectName("line_max")
        self.btn_uygula = QtWidgets.QPushButton(Dialog)
        self.btn_uygula.setGeometry(QtCore.QRect(100, 300, 111, 31))
        self.btn_uygula.setObjectName("btn_uygula")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_LimitSil = QtWidgets.QPushButton(Dialog)
        self.btn_LimitSil.setGeometry(QtCore.QRect(280, 300, 121, 31))
        self.btn_LimitSil.setObjectName("btn_LimitSil")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_uygula.setText(_translate("Dialog", "Uygula"))
        self.label.setText(_translate("Dialog", "Min Değer"))
        self.label_2.setText(_translate("Dialog", "Max Değer"))
        self.btn_LimitSil.setText(_translate("Dialog", "Limitleri Sil"))
        self.label_3.setText(_translate("Dialog", "Limit Ayarları"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
